In [42]:
from sgp4.api import SGP4_ERRORS

from astropy.coordinates import TEME, CartesianRepresentation  # CartesianDifferential
from astropy import units as u
from astropy.coordinates import ITRS

import pymap3d as pm

import pandas as pd
from sgp4 import omm
from sgp4.api import Satrec
from astropy.time import Time
from astropy.time import TimeDelta
import time
import numpy as np

class PropagInit:
    def __init__(self, satellite, lc, sample_time=1):
        self.satellite = satellite
        self.lc = lc
        self.sample_time = sample_time

        self.tempo = []
        self.traj = []
        self.dist = []
        self.hdmin = []
        self.dmin = []
        self.hrmin = []

    def searchh0(self, t_inic, t_final, distmin, distmin2,  n):

        enu_dv = []
        tv = []
        enu_pv = []
        flagmin = True
        ntraj = 0

        tvar = t_inic

        hr = 0
        hrmin = 0

        for i in range(0, n):
            error_code, teme_p, teme_v = self.satellite.sgp4(tvar.jd1, tvar.jd2)
            if error_code != 0:
                # raise RuntimeError(SGP4_ERRORS[error_code])
                print(" SGP4_ERRORS: {}\n".format(SGP4_ERRORS[error_code]))
                break
            teme_p = CartesianRepresentation(teme_p * u.km)
            teme = TEME(teme_p, obstime=tvar)  # ver diferença entre UT1 e UTC
            itrsp = teme.transform_to(ITRS(obstime=tvar))
            location = itrsp.earth_location
            # location.geodetic
            enu_p = pm.ecef2enu(1000 * location.x.value, 1000 * location.y.value, 1000 * location.z.value, self.lc.lat,
                                self.lc.lon, self.lc.height)
            enu_d = (enu_p[0]**2 + enu_p[1]**2 + enu_p[2]**2)**0.5

            if enu_d > distmin:
                tsample = round(1+abs((enu_d - distmin)/10000))
                print("sample = {}".format(tsample))
                if not flagmin:
                    flagmin = True
                    self.tempo.append(tv)
                    self.traj.append(enu_pv)
                    self.dist.append(enu_dv)
                    self.hdmin.append(hdmin)
                    self.dmin.append(dmin)
                    self.hrmin.append(hrmin)
                    tv = []
                    enu_pv = []
                    enu_dv = []
                hr = 0
                hrmin = 0
            else:
                tsample = self.sample_time
                tv.append(tvar)
                enu_dv.append(enu_d)
                enu_pv.append(enu_p)
                # print('{} {:.3f}'.format(tvar.value, enu_d))
                if (enu_dv[len(enu_dv)-2] < enu_dv[len(enu_dv)-1]) and flagmin:
                    dmin = enu_dv[len(enu_dv) - 2]
                    if dmin < distmin2:
                        hdmin = tvar - TimeDelta(tsample * u.s)
                        hrmin = hr - 1
                        flagmin = False
                        ntraj += 1
                        print('NORAD: {}, H0: {}, dmin= {:.3f}'.format(self.satellite.satnum, tv[0].value, dmin))
                    else:
                        tsample = 60*5

            hr += 1
            tvar += TimeDelta(tsample * u.s) # tsample  / (60 * 60 * 24)

            if tvar > t_final: # Time.strptime('2021-8-25 19:00:00', '%Y-%m-%d %H:%M:%S'):
                print("fim loop")
                break
        return self

    def searchh01(self, t_inic, t_final, distmin, distmin2,  n):

        enu_dv = []
        tv = []
        enu_pv = []
        flagmin = True
        ntraj = 0

        tvar = t_inic

        hr = 0
        hrmin = 0

        for i in range(0, n):
            error_code, teme_p, teme_v = self.satellite.sgp4(tvar.jd1, tvar.jd2)
            if error_code != 0:
                # raise RuntimeError(SGP4_ERRORS[error_code])
                print(" SGP4_ERRORS: {}\n".format(SGP4_ERRORS[error_code]))
                break
            teme_p = CartesianRepresentation(teme_p * u.km)
            teme = TEME(teme_p, obstime=tvar)  # ver diferença entre UT1 e UTC
            itrsp = teme.transform_to(ITRS(obstime=tvar))
            location = itrsp.earth_location
            # location.geodetic
            enu_p = pm.ecef2enu(1000 * location.x.value, 1000 * location.y.value, 1000 * location.z.value, self.lc.lat,
                                self.lc.lon, self.lc.height)
            enu_d = (enu_p[0]**2 + enu_p[1]**2 + enu_p[2]**2)**0.5

            # if enu_d < distmin:
            #     print('ok')
            if (enu_d - distmin)>0:
                tsample = round(5+abs(1*(enu_d - distmin)/8000))
            else:
                tsample = round(5+abs(2*(enu_d - distmin)/8000))            

            print("sample = {}, dist = {}".format(tsample,enu_d ))

            tvar += TimeDelta(tsample * u.s) # tsample  / (60 * 60 * 24)

            if tvar > t_final: # Time.strptime('2021-8-25 19:00:00', '%Y-%m-%d %H:%M:%S'):
                print("fim loop")
                break
        return self

    def searchh02(self, t_inic, t_final, distmin, distmin2,  n):

        enu_dv = []
        tv = []
        enu_pv = []
        flagmin = True
        ntraj = 0

        sign = 1

        tvar = t_inic

        hr = 0
        hrmin = 0

        for i in range(0, n):
            error_code, teme_p, teme_v = self.satellite.sgp4(tvar.jd1, tvar.jd2)
            if error_code != 0:
                # raise RuntimeError(SGP4_ERRORS[error_code])
                print(" SGP4_ERRORS: {}\n".format(SGP4_ERRORS[error_code]))
                break
            teme_p = CartesianRepresentation(teme_p * u.km)
            teme = TEME(teme_p, obstime=tvar)  # ver diferença entre UT1 e UTC
            itrsp = teme.transform_to(ITRS(obstime=tvar))
            location = itrsp.earth_location
            # location.geodetic
            enu_p = pm.ecef2enu(1000 * location.x.value, 1000 * location.y.value, 1000 * location.z.value, self.lc.lat,
                                self.lc.lon, self.lc.height)
            enu_d = (enu_p[0]**2 + enu_p[1]**2 + enu_p[2]**2)**0.5

            # if enu_d < distmin:
            #     print('ok')
            if (enu_d - distmin)>0:
                tsample = sign * round(5+abs(1*(enu_d - distmin)/8000))
            else:
                tvar += TimeDelta(60*10 * u.s)
                if sign > 0:  sign = -1
                else: sign = 1                              

            print("sample = {}, dist = {}".format(tsample,enu_d ))

            tvar += TimeDelta(tsample * u.s) # tsample  / (60 * 60 * 24)

            if tvar > t_final: # Time.strptime('2021-8-25 19:00:00', '%Y-%m-%d %H:%M:%S'):
                print("fim loop")
                break
        return self

    def pos_calc(self,tvar):
        error_code, teme_p, teme_v = self.satellite.sgp4(tvar.jd1, tvar.jd2)
        teme_p = CartesianRepresentation(teme_p * u.km)
        teme = TEME(teme_p, obstime=tvar)  # ver diferença entre UT1 e UTC
        itrsp = teme.transform_to(ITRS(obstime=tvar))
        location = itrsp.earth_location
        # location.geodetic
        enu_p = pm.ecef2enu(1000 * location.x.value, 1000 * location.y.value, 1000 * location.z.value, self.lc.lat,
                            self.lc.lon, self.lc.height)
        enu_d = (enu_p[0]**2 + enu_p[1]**2 + enu_p[2]**2)**0.5
        return enu_p, enu_d

class LocalFrame:
    def __init__(self, lat, lon, height):
        self.lat = lat
        self.lon = lon
        self.height = height

## Encontrar H0 atual:

In [ ]:


orbital_elem = pd.read_csv("orbital_elem.csv").to_dict('records')
lc = LocalFrame(-5.923654, -35.167755, 50)

satellite = Satrec()
omm.initialize(satellite, orbital_elem[20])

posit = PropagInit(satellite,lc)


t_inic=Time('2022-08-10T00:00:00.000', format='isot', scale='utc')     # momento de inicio da busca
t_final= Time('2022-08-12T00:00:00.000', format='isot', scale='utc')   # momento de parar a busca

ini = time.time()
posit.searchh02(t_inic, t_final, 1100*1000,  1000*1000,  10000)
fim = time.time()
print("Tempo: ", fim - ini)

In [ ]:
posit.tempo

In [13]:
orbital_elem[20]['TLE_LINE1']

'1 41335U 16011A   22222.69171522  .00000046  00000-0  37168-4 0  9997'

In [15]:
orbital_elem[20]['TLE_LINE2']

'2 41335  98.6197 289.1969 0001170  98.9531 261.1782 14.26739266337507'

## Encontrar H0 rápido:

In [93]:
from skyfield.api import load, wgs84

tles1 = load.tle_file('conftle.txt')

#tles2 = load.tle_file()

sat = tles1[0]
print(sat)

ini = time.time()

ts = load.timescale()

bluffton = wgs84.latlon(-5.92256, -35.1615)
t0 = ts.utc(2022, 8, 10)
t1 = ts.utc(2022, 8, 12)
t, events = sat.find_events(bluffton, t0, t1, altitude_degrees=30.0)

fim = time.time()
print("Tempo: ", fim - ini)

ini = time.time()
for ti, event in zip(t, events):
    #name = ('rise above 30°', 'culminate', 'set below 30°')[event]
    #print(ti.utc_strftime('%Y-%m-%dT%H:%M:%S'), name)

    tem = Time(ti.utc_strftime('%Y-%m-%dT%H:%M:%S'), format='isot')
    enup, enud = posit.pos_calc(tem) ## Lento
    #print(enup)
fim = time.time()
print("Tempo teme to enu: ", fim - ini)

catalog #41335 epoch 2022-08-10 16:36:04 UTC
Tempo:  0.0070002079010009766
Tempo teme to enu:  0.016000032424926758


## Código Rápido:

In [95]:


tem = Time(t.utc_strftime('%Y-%m-%dT%H:%M:%S'), format='isot')

ini = time.time()

error_code, teme_p, teme_v = satellite.sgp4_array(tem.jd1, tem.jd2)

teme_p = np.array(teme_p)
x, y, z = teme_p[:,0], teme_p[:,1], teme_p[:,2]

teme_p = CartesianRepresentation(x*u.km, y*u.km, z*u.km)
teme = TEME(teme_p, obstime=tem)  # ver diferença entre UT1 e UTC
itrsp = teme.transform_to(ITRS(obstime=tem))
location = itrsp.earth_location
enu_p = pm.ecef2enu(1000 * location.x.value, 1000 * location.y.value, 1000 * location.z.value, lc.lat,
                            lc.lon, lc.height)

fim = time.time()
print("Tempo: ", fim - ini)

enu_p

Tempo:  0.003001689910888672


(array([   25466.06337329,  -234535.48500898,  -485454.81320164,
         -878175.99713957, -1024634.30626479, -1164614.57977876,
          780143.46398059,   540860.39993516,   290103.4642783 ]),
 array([ 1216598.09923688,    51033.27412469, -1116505.87515824,
         -843261.56259651,  -250690.24273257,   343486.73060408,
          927915.67102392,  -127756.80189316, -1188335.8860551 ]),
 array([700461.93302992, 802338.92532322, 704343.79299177, 704159.42803241,
        729241.30021246, 702741.30093862, 701815.80867844, 785162.04318144,
        703506.06784671]))